// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/24/2026, 5:41:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/plugins/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/composables/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/utils/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;