// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/25/2026, 11:24:40 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/fawwaz/Publik/coding/ts/2026/myArticle/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/plugins/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/composables/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/utils/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/ts/2026/myArticle/front/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;