// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/2/2026, 10:34:08 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/plugins/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/composables/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/utils/**/*.{js,ts,mjs}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/fawwaz/Publik/coding/project/2026/myArticle/frontend/app.config.{js,ts,mjs}"]}},
{"content":["./components/**/*.{vue,ts}","./layouts/**/*.vue","./pages/**/*.vue","./plugins/**/*.{js,ts}","./nuxt.config.{js,ts}"]}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;